version: "3.8"

services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: colour-server
        container_name: colour-node-server
        command: npm start
        volumes:
          - ./server/:/usr/app
          - /usr/src/app/node_modules
        ports:
          - "3000:3000"
        env_file: ./server/.env
        environment:
          - NODE_ENV=development
        depends_on:
          - db
    db:
      image: mongo
      ports:
        - 27017:27017
      container_name: mongo-db
      volumes:
        - mongo-data:/data/db
volumes:
  mongo-data: