version: "3.8"

services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        image: colour-client
        container_name: colour-react-client
        volumes:
            - ./client/:/usr/app
            - /usr/app/node_modules
        depends_on:
            - server
        ports:
            - "3000:3000"

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: colour-server
        container_name: colour-node-server
        command: npm start
        volumes:
          - ./server/:/usr/app
          - /usr/src/app/node_modules
        ports:
          - "4000:4000"
        env_file: ./server/.env
        environment:
          - NODE_ENV=development
        depends_on:
          - db
    db:
      image: mongo
      ports:
        - 27017:27017
      container_name: mongo-db
      volumes:
        - mongo-data:/data/db
volumes:
  mongo-data: